# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs
Plate.destroy_all
Ingredient.destroy_all
RegimePlate.destroy_all
Patient.destroy_all
DayRegime.destroy_all
Area.destroy_all


Area.create([
  { :nombre => "reposteria", :descripcion => nil, :created_at => "2013-06-27 03:03:54", :updated_at => "2013-06-27 03:03:54" },
  { :nombre => "Cocina fria", :descripcion => nil, :created_at => "2013-06-27 03:03:54", :updated_at => "2013-06-27 03:03:54" },
  { :nombre => "Carnes", :descripcion => nil, :created_at => "2013-06-27 03:03:54", :updated_at => "2013-06-27 03:03:54" },
  { :nombre => "Verduras", :descripcion => nil, :created_at => "2013-06-27 03:03:54", :updated_at => "2013-06-27 03:03:54" },
  { :nombre => "Otros", :descripcion => nil, :created_at => "2013-06-27 03:03:55", :updated_at => "2013-06-27 03:03:55" }
], :without_protection => true )



AreasPlates.create([
  { :area_id => 32, :plate_id => 410 },
  { :area_id => 34, :plate_id => 411 },
  { :area_id => 31, :plate_id => 422 },
  { :area_id => 31, :plate_id => 424 },
  { :area_id => 34, :plate_id => 435 },
  { :area_id => 32, :plate_id => 427 },
  { :area_id => 33, :plate_id => 428 },
  { :area_id => 33, :plate_id => 429 },
  { :area_id => 34, :plate_id => 429 },
  { :area_id => 32, :plate_id => 426 },
  { :area_id => 31, :plate_id => 421 },
  { :area_id => 35, :plate_id => 410 },
  { :area_id => 35, :plate_id => 414 },
  { :area_id => 35, :plate_id => 418 },
  { :area_id => 35, :plate_id => 422 },
  { :area_id => 35, :plate_id => 426 },
  { :area_id => 35, :plate_id => 430 },
  { :area_id => 35, :plate_id => 434 },
  { :area_id => 31, :plate_id => 423 }
], :without_protection => true )



DayRegime.create([
  { :date => "2013-06-27", :regime_day => 2, :created_at => "2013-06-27 03:04:08", :updated_at => "2013-06-27 04:09:11" }
], :without_protection => true )



Ingredient.create([
  { :nombre => "carne", :precio => 250, :unidad => "gramos", :created_at => "2013-06-27 03:04:03", :updated_at => "2013-06-27 03:04:03" },
  { :nombre => "arroz", :precio => 100, :unidad => "gramos", :created_at => "2013-06-27 03:04:03", :updated_at => "2013-06-27 03:04:03" },
  { :nombre => "lechuga", :precio => 100, :unidad => "gramos", :created_at => "2013-06-27 03:04:03", :updated_at => "2013-06-27 03:04:03" },
  { :nombre => "papas", :precio => 200, :unidad => "gramos", :created_at => "2013-06-27 03:04:03", :updated_at => "2013-06-27 03:04:03" },
  { :nombre => "cebolla", :precio => 150, :unidad => "gramos", :created_at => "2013-06-27 03:04:04", :updated_at => "2013-06-27 03:04:04" },
  { :nombre => "pollo", :precio => 450, :unidad => "gramos", :created_at => "2013-06-27 03:04:04", :updated_at => "2013-06-27 03:04:04" },
  { :nombre => "champiñones", :precio => 450, :unidad => "gramos", :created_at => "2013-06-27 03:04:04", :updated_at => "2013-06-27 03:04:04" },
  { :nombre => "reineta", :precio => 450, :unidad => "gramos", :created_at => "2013-06-27 03:04:04", :updated_at => "2013-06-27 03:04:04" },
  { :nombre => "aceite", :precio => 10, :unidad => "ml", :created_at => "2013-06-27 03:04:05", :updated_at => "2013-06-27 03:04:05" },
  { :nombre => "sal", :precio => 5, :unidad => "gramos", :created_at => "2013-06-27 03:04:05", :updated_at => "2013-06-27 03:04:05" }
], :without_protection => true )



Order.create([
  { :horario => 1, :comentarios => "", :created_at => "2013-06-10 01:43:24", :updated_at => "2013-06-10 01:43:24", :order_list_id => 2, :regime_id => nil },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-10 16:50:17", :updated_at => "2013-06-10 16:50:17", :order_list_id => 2, :regime_id => nil },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-10 16:50:32", :updated_at => "2013-06-10 16:50:32", :order_list_id => 2, :regime_id => nil },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-10 16:50:55", :updated_at => "2013-06-10 16:50:55", :order_list_id => 2, :regime_id => nil },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:45", :updated_at => "2013-06-12 16:46:45", :order_list_id => 3, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:45", :updated_at => "2013-06-12 16:46:45", :order_list_id => 4, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:45", :updated_at => "2013-06-12 16:46:45", :order_list_id => 5, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:45", :updated_at => "2013-06-12 16:46:45", :order_list_id => 6, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:46", :updated_at => "2013-06-12 16:46:46", :order_list_id => 7, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:46", :updated_at => "2013-06-12 16:46:46", :order_list_id => 8, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:50:58", :updated_at => "2013-06-12 16:50:58", :order_list_id => 9, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-12 16:50:58", :updated_at => "2013-06-12 16:50:58", :order_list_id => 10, :regime_id => 1 },
  { :horario => 4, :comentarios => nil, :created_at => "2013-06-12 16:50:58", :updated_at => "2013-06-12 16:50:58", :order_list_id => 11, :regime_id => 1 },
  { :horario => 8, :comentarios => nil, :created_at => "2013-06-12 16:50:58", :updated_at => "2013-06-12 16:50:58", :order_list_id => 12, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:50:59", :updated_at => "2013-06-12 16:50:59", :order_list_id => 13, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-12 16:50:59", :updated_at => "2013-06-12 16:50:59", :order_list_id => 14, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-26 17:41:43", :updated_at => "2013-06-26 17:41:43", :order_list_id => 15, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-26 17:41:43", :updated_at => "2013-06-26 17:41:43", :order_list_id => 16, :regime_id => 1 },
  { :horario => 4, :comentarios => nil, :created_at => "2013-06-26 17:41:44", :updated_at => "2013-06-26 17:41:44", :order_list_id => 17, :regime_id => 1 },
  { :horario => 8, :comentarios => nil, :created_at => "2013-06-26 17:41:44", :updated_at => "2013-06-26 17:41:44", :order_list_id => 18, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-26 17:41:44", :updated_at => "2013-06-26 17:41:44", :order_list_id => 19, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-26 17:41:44", :updated_at => "2013-06-26 17:41:44", :order_list_id => 20, :regime_id => 1 },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-26 20:20:34", :updated_at => "2013-06-26 20:20:35", :order_list_id => 22, :regime_id => 1 },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-26 20:20:59", :updated_at => "2013-06-26 20:21:01", :order_list_id => 22, :regime_id => 1 },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-26 20:21:11", :updated_at => "2013-06-26 20:21:12", :order_list_id => 22, :regime_id => 1 },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-26 20:21:24", :updated_at => "2013-06-26 20:21:25", :order_list_id => 22, :regime_id => 1 },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-26 20:56:07", :updated_at => "2013-06-26 20:56:08", :order_list_id => 24, :regime_id => 1 },
  { :horario => 2, :comentarios => "Sin Sal", :created_at => "2013-06-26 20:56:25", :updated_at => "2013-06-26 20:56:26", :order_list_id => 24, :regime_id => 1 },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-26 20:56:42", :updated_at => "2013-06-26 20:56:42", :order_list_id => 24, :regime_id => 2 },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-26 22:21:37", :updated_at => "2013-06-26 22:21:39", :order_list_id => 25, :regime_id => 1 },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-26 22:21:48", :updated_at => "2013-06-26 22:21:48", :order_list_id => 25, :regime_id => nil },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-26 22:22:04", :updated_at => "2013-06-26 22:22:05", :order_list_id => 25, :regime_id => 1 },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-26 22:22:16", :updated_at => "2013-06-26 22:22:18", :order_list_id => 25, :regime_id => 1 },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-26 22:23:04", :updated_at => "2013-06-26 22:23:05", :order_list_id => 26, :regime_id => 2 },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-26 22:23:20", :updated_at => "2013-06-26 22:23:21", :order_list_id => 26, :regime_id => 1 },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-26 22:23:32", :updated_at => "2013-06-26 22:23:33", :order_list_id => 26, :regime_id => 1 },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-26 22:23:46", :updated_at => "2013-06-26 22:23:47", :order_list_id => 26, :regime_id => 1 },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-26 22:25:09", :updated_at => "2013-06-26 22:25:09", :order_list_id => 27, :regime_id => nil },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-26 22:25:20", :updated_at => "2013-06-26 22:25:21", :order_list_id => 27, :regime_id => 1 },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-26 22:25:31", :updated_at => "2013-06-26 22:25:31", :order_list_id => 27, :regime_id => 1 },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-26 22:25:43", :updated_at => "2013-06-26 22:25:44", :order_list_id => 27, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-27 03:04:10", :updated_at => "2013-06-27 03:04:10", :order_list_id => 33, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-27 03:04:10", :updated_at => "2013-06-27 03:04:10", :order_list_id => 34, :regime_id => 1 },
  { :horario => 4, :comentarios => nil, :created_at => "2013-06-27 03:04:11", :updated_at => "2013-06-27 03:04:11", :order_list_id => 35, :regime_id => 1 },
  { :horario => 8, :comentarios => nil, :created_at => "2013-06-27 03:04:11", :updated_at => "2013-06-27 03:04:11", :order_list_id => 36, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-27 03:04:11", :updated_at => "2013-06-27 03:04:11", :order_list_id => 37, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-27 03:04:12", :updated_at => "2013-06-27 03:04:12", :order_list_id => 38, :regime_id => 1 },
  { :horario => 1, :comentarios => "]", :created_at => "2013-06-27 03:56:54", :updated_at => "2013-06-27 03:56:54", :order_list_id => 64, :regime_id => nil },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-27 03:57:11", :updated_at => "2013-06-27 03:57:11", :order_list_id => 64, :regime_id => nil },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-27 03:57:29", :updated_at => "2013-06-27 03:57:29", :order_list_id => 64, :regime_id => nil },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-27 04:12:12", :updated_at => "2013-06-27 04:12:14", :order_list_id => 65, :regime_id => 1 },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-27 04:14:20", :updated_at => "2013-06-27 04:14:21", :order_list_id => 65, :regime_id => 1 },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-27 04:14:34", :updated_at => "2013-06-27 04:14:35", :order_list_id => 65, :regime_id => 1 },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-27 04:14:48", :updated_at => "2013-06-27 04:14:50", :order_list_id => 65, :regime_id => 1 },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-27 04:59:37", :updated_at => "2013-06-27 04:59:39", :order_list_id => 68, :regime_id => 1 },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-27 04:59:49", :updated_at => "2013-06-27 04:59:50", :order_list_id => 68, :regime_id => 1 },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-27 05:02:13", :updated_at => "2013-06-27 05:02:14", :order_list_id => 70, :regime_id => 1 },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-27 05:02:33", :updated_at => "2013-06-27 05:02:34", :order_list_id => 70, :regime_id => 1 },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-27 05:02:42", :updated_at => "2013-06-27 05:02:43", :order_list_id => 70, :regime_id => 1 },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-27 05:03:02", :updated_at => "2013-06-27 05:03:04", :order_list_id => 70, :regime_id => 1 },
  { :horario => 1, :comentarios => "Palta sin sal", :created_at => "2013-06-27 05:04:07", :updated_at => "2013-06-27 05:04:09", :order_list_id => 72, :regime_id => 3 },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-27 05:04:19", :updated_at => "2013-06-27 05:04:20", :order_list_id => 72, :regime_id => 3 },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-27 05:04:29", :updated_at => "2013-06-27 05:04:30", :order_list_id => 72, :regime_id => 3 },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-27 05:04:52", :updated_at => "2013-06-27 05:04:54", :order_list_id => 72, :regime_id => 3 },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-27 05:11:48", :updated_at => "2013-06-27 05:11:50", :order_list_id => 74, :regime_id => 2 },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-27 05:12:01", :updated_at => "2013-06-27 05:12:02", :order_list_id => 74, :regime_id => 2 },
  { :horario => 4, :comentarios => "", :created_at => "2013-06-27 05:12:11", :updated_at => "2013-06-27 05:12:12", :order_list_id => 74, :regime_id => 2 },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-27 05:12:24", :updated_at => "2013-06-27 05:12:25", :order_list_id => 74, :regime_id => 2 }
], :without_protection => true )



OrderList.create([
  { :patient_id => 53, :esPaciente => true, :created_at => "2013-06-27 04:11:30", :updated_at => "2013-06-27 04:11:43", :fecha => "2013-06-27", :dia => 2 },
  { :patient_id => nil, :esPaciente => nil, :created_at => "2013-06-27 04:57:31", :updated_at => "2013-06-27 04:57:31", :fecha => "2013-06-28", :dia => nil },
  { :patient_id => nil, :esPaciente => nil, :created_at => "2013-06-27 04:58:46", :updated_at => "2013-06-27 04:58:46", :fecha => "2013-06-28", :dia => nil },
  { :patient_id => 52, :esPaciente => false, :created_at => "2013-06-27 04:58:55", :updated_at => "2013-06-27 04:59:16", :fecha => "2013-06-27", :dia => 2 },
  { :patient_id => nil, :esPaciente => nil, :created_at => "2013-06-27 05:00:23", :updated_at => "2013-06-27 05:00:23", :fecha => "2013-06-27", :dia => nil },
  { :patient_id => 54, :esPaciente => true, :created_at => "2013-06-27 05:00:32", :updated_at => "2013-06-27 05:00:42", :fecha => "2013-06-27", :dia => 2 },
  { :patient_id => nil, :esPaciente => nil, :created_at => "2013-06-27 05:03:20", :updated_at => "2013-06-27 05:03:20", :fecha => "2013-06-27", :dia => nil },
  { :patient_id => 55, :esPaciente => true, :created_at => "2013-06-27 05:03:26", :updated_at => "2013-06-27 05:03:37", :fecha => "2013-06-27", :dia => 2 },
  { :patient_id => nil, :esPaciente => nil, :created_at => "2013-06-27 05:11:13", :updated_at => "2013-06-27 05:11:13", :fecha => "2013-06-28", :dia => nil },
  { :patient_id => 53, :esPaciente => false, :created_at => "2013-06-27 05:11:19", :updated_at => "2013-06-27 05:11:33", :fecha => "2013-06-27", :dia => 2 }
], :without_protection => true )



Patient.create([
  { :nombre => "Pedro A", :num_pieza => "1A", :created_at => "2013-06-27 03:04:07", :updated_at => "2013-06-27 03:04:07", :rut => "17753853-4", :detalles => nil },
  { :nombre => "Rodrigo A", :num_pieza => "2A", :created_at => "2013-06-27 03:04:07", :updated_at => "2013-06-27 03:57:29", :rut => "17753345-8", :detalles => "guguiho ioj" },
  { :nombre => "Fernando E", :num_pieza => "3A", :created_at => "2013-06-27 03:04:07", :updated_at => "2013-06-27 05:02:33", :rut => "13753853-3", :detalles => "" },
  { :nombre => "Joaquin F", :num_pieza => "4A", :created_at => "2013-06-27 03:04:08", :updated_at => "2013-06-27 05:04:07", :rut => "16753853-2", :detalles => "" },
  { :nombre => "Vicente V", :num_pieza => "5A", :created_at => "2013-06-27 03:04:08", :updated_at => "2013-06-27 03:04:08", :rut => "13753853-1", :detalles => nil }
], :without_protection => true )



Plate.create([
  { :nombre => "Cafe", :calorias => nil, :tipo => 1, :created_at => "2013-06-27 03:03:55", :updated_at => "2013-06-27 04:24:46", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Te", :calorias => nil, :tipo => 1, :created_at => "2013-06-27 03:03:55", :updated_at => "2013-06-27 03:03:55", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Pan", :calorias => nil, :tipo => 2, :created_at => "2013-06-27 03:03:55", :updated_at => "2013-06-27 03:03:55", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Jamon", :calorias => nil, :tipo => 3, :created_at => "2013-06-27 03:03:56", :updated_at => "2013-06-27 04:25:05", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Palta", :calorias => nil, :tipo => 3, :created_at => "2013-06-27 03:03:56", :updated_at => "2013-06-27 04:25:23", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Tortilla Francesa", :calorias => nil, :tipo => 3, :created_at => "2013-06-27 03:03:56", :updated_at => "2013-06-27 03:03:56", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Queso", :calorias => nil, :tipo => 3, :created_at => "2013-06-27 03:03:57", :updated_at => "2013-06-27 03:03:57", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Mantequilla", :calorias => nil, :tipo => 4, :created_at => "2013-06-27 03:03:57", :updated_at => "2013-06-27 03:03:57", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Mermelada", :calorias => nil, :tipo => 4, :created_at => "2013-06-27 03:03:57", :updated_at => "2013-06-27 03:03:57", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Manjar", :calorias => nil, :tipo => 4, :created_at => "2013-06-27 03:03:57", :updated_at => "2013-06-27 03:03:57", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Miel", :calorias => nil, :tipo => 4, :created_at => "2013-06-27 03:03:58", :updated_at => "2013-06-27 03:03:58", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Jugo naranja", :calorias => nil, :tipo => 5, :created_at => "2013-06-27 03:03:58", :updated_at => "2013-06-27 03:03:58", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Yogurt", :calorias => nil, :tipo => 5, :created_at => "2013-06-27 03:03:58", :updated_at => "2013-06-27 03:03:58", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Yogurt", :calorias => nil, :tipo => 5, :created_at => "2013-06-27 03:03:58", :updated_at => "2013-06-27 03:03:58", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Pie de limon", :calorias => nil, :tipo => 6, :created_at => "2013-06-27 03:03:59", :updated_at => "2013-06-27 04:28:30", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "2 Palmeritas", :calorias => nil, :tipo => 6, :created_at => "2013-06-27 03:03:59", :updated_at => "2013-06-27 04:25:42", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Bollo", :calorias => nil, :tipo => 6, :created_at => "2013-06-27 03:03:59", :updated_at => "2013-06-27 05:22:31", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Galletas", :calorias => nil, :tipo => 6, :created_at => "2013-06-27 03:03:59", :updated_at => "2013-06-27 04:26:00", :horario => 5, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Consome", :calorias => nil, :tipo => 7, :created_at => "2013-06-27 03:04:00", :updated_at => "2013-06-27 03:04:00", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Albahaca y dados de tomate, palta, queso fresco", :calorias => nil, :tipo => 7, :created_at => "2013-06-27 03:04:00", :updated_at => "2013-06-27 04:28:02", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Quiche loreine", :calorias => nil, :tipo => 7, :created_at => "2013-06-27 03:04:00", :updated_at => "2013-06-27 04:27:06", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Reineta al horno", :calorias => nil, :tipo => 8, :created_at => "2013-06-27 03:04:00", :updated_at => "2013-06-27 04:27:24", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Bistec de lomo c/ salsa champiñon", :calorias => nil, :tipo => 8, :created_at => "2013-06-27 03:04:01", :updated_at => "2013-06-27 04:27:41", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Verduras a la mantequilla: Zapallito, zanahoria, champiñones", :calorias => nil, :tipo => 9, :created_at => "2013-06-27 03:04:01", :updated_at => "2013-06-27 03:04:01", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Arroz", :calorias => nil, :tipo => 9, :created_at => "2013-06-27 03:04:01", :updated_at => "2013-06-27 04:26:48", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Pure", :calorias => nil, :tipo => 9, :created_at => "2013-06-27 03:04:02", :updated_at => "2013-06-27 03:04:02", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Verduras a la mantequilla: Zapallito, zanahoria, champiñones", :calorias => nil, :tipo => 9, :created_at => "2013-06-27 03:04:02", :updated_at => "2013-06-27 03:04:02", :horario => 10, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Helado", :calorias => nil, :tipo => 10, :created_at => "2013-06-27 03:04:02", :updated_at => "2013-06-27 03:04:02", :horario => 2, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." },
  { :nombre => "Fruta", :calorias => nil, :tipo => 10, :created_at => "2013-06-27 03:04:02", :updated_at => "2013-06-27 04:26:18", :horario => 2, :description => "Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, legimus senserit definiebas an eos." }
], :without_protection => true )



PlateIngredient.create([
  { :cantidad => 5, :created_at => "2013-06-06 14:30:50", :updated_at => "2013-06-06 14:30:50", :plate_id => 141, :ingredient_id => 28 },
  { :cantidad => 5, :created_at => "2013-06-06 14:30:50", :updated_at => "2013-06-06 14:30:50", :plate_id => 141, :ingredient_id => 35 },
  { :cantidad => 5, :created_at => "2013-06-06 14:30:50", :updated_at => "2013-06-06 14:30:50", :plate_id => 141, :ingredient_id => 36 },
  { :cantidad => 3, :created_at => "2013-06-06 14:30:50", :updated_at => "2013-06-06 14:30:50", :plate_id => 138, :ingredient_id => 34 },
  { :cantidad => 2, :created_at => "2013-06-06 14:30:51", :updated_at => "2013-06-06 14:30:51", :plate_id => 139, :ingredient_id => 27 },
  { :cantidad => 2, :created_at => "2013-06-06 14:30:51", :updated_at => "2013-06-06 14:30:51", :plate_id => 139, :ingredient_id => 33 },
  { :cantidad => 5, :created_at => "2013-06-06 15:07:37", :updated_at => "2013-06-06 15:07:37", :plate_id => 170, :ingredient_id => 38 },
  { :cantidad => 5, :created_at => "2013-06-06 15:07:37", :updated_at => "2013-06-06 15:07:37", :plate_id => 170, :ingredient_id => 45 },
  { :cantidad => 5, :created_at => "2013-06-06 15:07:38", :updated_at => "2013-06-06 15:07:38", :plate_id => 170, :ingredient_id => 46 },
  { :cantidad => 3, :created_at => "2013-06-06 15:07:38", :updated_at => "2013-06-06 15:07:38", :plate_id => 167, :ingredient_id => 44 },
  { :cantidad => 2, :created_at => "2013-06-06 15:07:38", :updated_at => "2013-06-06 15:07:38", :plate_id => 168, :ingredient_id => 37 },
  { :cantidad => 2, :created_at => "2013-06-06 15:07:38", :updated_at => "2013-06-06 15:07:38", :plate_id => 168, :ingredient_id => 43 },
  { :cantidad => 5, :created_at => "2013-06-06 15:12:32", :updated_at => "2013-06-06 15:12:32", :plate_id => 199, :ingredient_id => 48 },
  { :cantidad => 5, :created_at => "2013-06-06 15:12:32", :updated_at => "2013-06-06 15:12:32", :plate_id => 199, :ingredient_id => 55 },
  { :cantidad => 5, :created_at => "2013-06-06 15:12:33", :updated_at => "2013-06-06 15:12:33", :plate_id => 199, :ingredient_id => 56 },
  { :cantidad => 3, :created_at => "2013-06-06 15:12:33", :updated_at => "2013-06-06 15:12:33", :plate_id => 196, :ingredient_id => 54 },
  { :cantidad => 2, :created_at => "2013-06-06 15:12:33", :updated_at => "2013-06-06 15:12:33", :plate_id => 197, :ingredient_id => 47 },
  { :cantidad => 2, :created_at => "2013-06-06 15:12:33", :updated_at => "2013-06-06 15:12:33", :plate_id => 197, :ingredient_id => 53 },
  { :cantidad => 5, :created_at => "2013-06-06 15:19:07", :updated_at => "2013-06-06 15:19:07", :plate_id => 228, :ingredient_id => 58 },
  { :cantidad => 5, :created_at => "2013-06-06 15:19:07", :updated_at => "2013-06-06 15:19:07", :plate_id => 228, :ingredient_id => 65 },
  { :cantidad => 5, :created_at => "2013-06-06 15:19:08", :updated_at => "2013-06-06 15:19:08", :plate_id => 228, :ingredient_id => 66 },
  { :cantidad => 3, :created_at => "2013-06-06 15:19:08", :updated_at => "2013-06-06 15:19:08", :plate_id => 225, :ingredient_id => 64 },
  { :cantidad => 2, :created_at => "2013-06-06 15:19:08", :updated_at => "2013-06-06 15:19:08", :plate_id => 226, :ingredient_id => 57 },
  { :cantidad => 2, :created_at => "2013-06-06 15:19:08", :updated_at => "2013-06-06 15:19:08", :plate_id => 226, :ingredient_id => 63 },
  { :cantidad => 2, :created_at => "2013-06-11 00:07:26", :updated_at => "2013-06-11 00:07:26", :plate_id => 226, :ingredient_id => 60 },
  { :cantidad => 5, :created_at => "2013-06-12 16:14:03", :updated_at => "2013-06-12 16:14:03", :plate_id => 257, :ingredient_id => 68 },
  { :cantidad => 5, :created_at => "2013-06-12 16:14:03", :updated_at => "2013-06-12 16:14:03", :plate_id => 257, :ingredient_id => 75 },
  { :cantidad => 5, :created_at => "2013-06-12 16:14:03", :updated_at => "2013-06-12 16:14:03", :plate_id => 257, :ingredient_id => 76 },
  { :cantidad => 3, :created_at => "2013-06-12 16:14:03", :updated_at => "2013-06-12 16:14:03", :plate_id => 254, :ingredient_id => 74 },
  { :cantidad => 2, :created_at => "2013-06-12 16:14:04", :updated_at => "2013-06-12 16:14:04", :plate_id => 255, :ingredient_id => 67 },
  { :cantidad => 2, :created_at => "2013-06-12 16:14:04", :updated_at => "2013-06-12 16:14:04", :plate_id => 255, :ingredient_id => 73 },
  { :cantidad => 5, :created_at => "2013-06-12 16:44:06", :updated_at => "2013-06-12 16:44:06", :plate_id => 286, :ingredient_id => 78 },
  { :cantidad => 5, :created_at => "2013-06-12 16:44:06", :updated_at => "2013-06-12 16:44:06", :plate_id => 286, :ingredient_id => 85 },
  { :cantidad => 5, :created_at => "2013-06-12 16:44:07", :updated_at => "2013-06-12 16:44:07", :plate_id => 286, :ingredient_id => 86 },
  { :cantidad => 3, :created_at => "2013-06-12 16:44:07", :updated_at => "2013-06-12 16:44:07", :plate_id => 283, :ingredient_id => 84 },
  { :cantidad => 2, :created_at => "2013-06-12 16:44:07", :updated_at => "2013-06-12 16:44:07", :plate_id => 284, :ingredient_id => 77 },
  { :cantidad => 2, :created_at => "2013-06-12 16:44:07", :updated_at => "2013-06-12 16:44:07", :plate_id => 284, :ingredient_id => 83 },
  { :cantidad => 5, :created_at => "2013-06-12 16:46:40", :updated_at => "2013-06-12 16:46:40", :plate_id => 315, :ingredient_id => 88 },
  { :cantidad => 5, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 315, :ingredient_id => 95 },
  { :cantidad => 5, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 315, :ingredient_id => 96 },
  { :cantidad => 3, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 312, :ingredient_id => 94 },
  { :cantidad => 2, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 313, :ingredient_id => 87 },
  { :cantidad => 2, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 313, :ingredient_id => 93 },
  { :cantidad => 5, :created_at => "2013-06-12 16:50:52", :updated_at => "2013-06-12 16:50:52", :plate_id => 344, :ingredient_id => 98 },
  { :cantidad => 5, :created_at => "2013-06-12 16:50:52", :updated_at => "2013-06-12 16:50:52", :plate_id => 344, :ingredient_id => 105 },
  { :cantidad => 5, :created_at => "2013-06-12 16:50:53", :updated_at => "2013-06-12 16:50:53", :plate_id => 344, :ingredient_id => 106 },
  { :cantidad => 3, :created_at => "2013-06-12 16:50:53", :updated_at => "2013-06-12 16:50:53", :plate_id => 341, :ingredient_id => 104 },
  { :cantidad => 2, :created_at => "2013-06-12 16:50:53", :updated_at => "2013-06-12 16:50:53", :plate_id => 342, :ingredient_id => 97 },
  { :cantidad => 2, :created_at => "2013-06-12 16:50:53", :updated_at => "2013-06-12 16:50:53", :plate_id => 342, :ingredient_id => 103 },
  { :cantidad => 5, :created_at => "2013-06-26 17:41:38", :updated_at => "2013-06-26 17:41:38", :plate_id => 402, :ingredient_id => 108 },
  { :cantidad => 5, :created_at => "2013-06-26 17:41:39", :updated_at => "2013-06-26 17:41:39", :plate_id => 402, :ingredient_id => 115 },
  { :cantidad => 5, :created_at => "2013-06-26 17:41:39", :updated_at => "2013-06-26 17:41:39", :plate_id => 402, :ingredient_id => 116 },
  { :cantidad => 3, :created_at => "2013-06-26 17:41:39", :updated_at => "2013-06-26 17:41:39", :plate_id => 399, :ingredient_id => 114 },
  { :cantidad => 2, :created_at => "2013-06-26 17:41:39", :updated_at => "2013-06-26 17:41:39", :plate_id => 400, :ingredient_id => 107 },
  { :cantidad => 2, :created_at => "2013-06-26 17:41:40", :updated_at => "2013-06-26 17:41:40", :plate_id => 400, :ingredient_id => 113 },
  { :cantidad => 5, :created_at => "2013-06-27 03:04:05", :updated_at => "2013-06-27 03:04:05", :plate_id => 431, :ingredient_id => 118 },
  { :cantidad => 5, :created_at => "2013-06-27 03:04:05", :updated_at => "2013-06-27 03:04:05", :plate_id => 431, :ingredient_id => 125 },
  { :cantidad => 5, :created_at => "2013-06-27 03:04:06", :updated_at => "2013-06-27 03:04:06", :plate_id => 431, :ingredient_id => 126 },
  { :cantidad => 3, :created_at => "2013-06-27 03:04:06", :updated_at => "2013-06-27 03:04:06", :plate_id => 428, :ingredient_id => 124 },
  { :cantidad => 2, :created_at => "2013-06-27 03:04:06", :updated_at => "2013-06-27 03:04:06", :plate_id => 429, :ingredient_id => 117 },
  { :cantidad => 2, :created_at => "2013-06-27 03:04:06", :updated_at => "2013-06-27 03:04:06", :plate_id => 429, :ingredient_id => 123 }
], :without_protection => true )



Regime.create([
  { :nombre => "Régimen para Diabetes", :created_at => "2013-05-24 13:14:13", :updated_at => "2013-06-26 19:47:05" },
  { :nombre => "Régimen liviano", :created_at => "2013-06-26 20:10:57", :updated_at => "2013-06-26 20:10:57" },
  { :nombre => "Régimen Normal", :created_at => "2013-06-27 04:16:22", :updated_at => "2013-06-27 04:16:22" }
], :without_protection => true )



RegimePlate.create([
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 407, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 408, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 409, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 411, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 412, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 410, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 414, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 418, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 419, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 421, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 422, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 425, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 426, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 429, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 428, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 430, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 431, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 432, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 434, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 435, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 407, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 408, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 409, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 421, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 422, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 426, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 427, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 428, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 429, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 431, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 433, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 434, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:08:28", :updated_at => "2013-06-27 04:08:28", :plate_id => 435, :regime_id => 1, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 407, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 408, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 409, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 410, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 411, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 414, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 416, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 418, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 420, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 421, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 422, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 424, :regime_id => 3, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 426, :regime_id => 3, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 425, :regime_id => 3, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 428, :regime_id => 3, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 429, :regime_id => 3, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 431, :regime_id => 3, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 435, :regime_id => 3, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 408, :regime_id => 3, :horario => 4 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 407, :regime_id => 3, :horario => 4 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 409, :regime_id => 3, :horario => 4 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 422, :regime_id => 3, :horario => 4 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 421, :regime_id => 3, :horario => 4 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 425, :regime_id => 3, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 426, :regime_id => 3, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 428, :regime_id => 3, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 428, :regime_id => 3, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 430, :regime_id => 3, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-27 04:17:41", :updated_at => "2013-06-27 04:17:41", :plate_id => 435, :regime_id => 3, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 407, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 408, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 409, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 410, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 411, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 415, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 418, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 421, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 422, :regime_id => 2, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 426, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 427, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 429, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 428, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 431, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 430, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 432, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 434, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 435, :regime_id => 2, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 407, :regime_id => 2, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 409, :regime_id => 2, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 421, :regime_id => 2, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 425, :regime_id => 2, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 429, :regime_id => 2, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 428, :regime_id => 2, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 430, :regime_id => 2, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 431, :regime_id => 2, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:20:50", :updated_at => "2013-06-27 04:20:50", :plate_id => 434, :regime_id => 2, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 407, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 408, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 409, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 411, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 412, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 415, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 416, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 418, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 422, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 421, :regime_id => 3, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 425, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 426, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 427, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 428, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 429, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 431, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 430, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 434, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 435, :regime_id => 3, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 407, :regime_id => 3, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 408, :regime_id => 3, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 409, :regime_id => 3, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 422, :regime_id => 3, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 421, :regime_id => 3, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 425, :regime_id => 3, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 426, :regime_id => 3, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 428, :regime_id => 3, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 429, :regime_id => 3, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 431, :regime_id => 3, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 430, :regime_id => 3, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 434, :regime_id => 3, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-27 04:22:41", :updated_at => "2013-06-27 04:22:41", :plate_id => 435, :regime_id => 3, :horario => 8 }
], :without_protection => true )



Report.create([
  { :name => "2013-06-26 18:24:35 -0400 CenaReport.pdf", :tipo => "1", :description => nil, :start => nil, :created_at => "2013-06-26 22:24:35", :updated_at => "2013-06-26 22:24:35" },
  { :name => "2013-06-26 18:26:08 -0400 CenaReport.pdf", :tipo => "1", :description => nil, :start => nil, :created_at => "2013-06-26 22:26:08", :updated_at => "2013-06-26 22:26:08" }
], :without_protection => true )



Role.create([
  { :name => "admin", :resource_id => nil, :resource_type => nil, :created_at => "2013-05-24 13:01:22", :updated_at => "2013-05-24 13:01:22" },
  { :name => "nutricionista", :resource_id => nil, :resource_type => nil, :created_at => "2013-05-24 13:01:23", :updated_at => "2013-05-24 13:01:23" },
  { :name => "cocina", :resource_id => nil, :resource_type => nil, :created_at => "2013-05-24 13:01:23", :updated_at => "2013-05-24 13:01:23" }
], :without_protection => true )



User.create([
  { :email => "user@example.com", :encrypted_password => "$2a$10$Esiq99QTQn5J/WJku3/AL.lUHfbLplRq0/qSBD6WeksAifIsN9gwe", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 18, :current_sign_in_at => "2013-06-27 05:33:55", :last_sign_in_at => "2013-06-26 18:42:00", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-05-24 13:01:23", :updated_at => "2013-06-27 05:33:55", :name => "First User", :rut => "12345678-9" }
], :without_protection => true )


