# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Area.create([
  { :nombre => "reposteria", :descripcion => nil, :created_at => "2013-06-26 17:41:28", :updated_at => "2013-06-26 17:41:28" },
  { :nombre => "Cocina fria", :descripcion => nil, :created_at => "2013-06-26 17:41:28", :updated_at => "2013-06-26 17:41:28" },
  { :nombre => "Carnes", :descripcion => nil, :created_at => "2013-06-26 17:41:28", :updated_at => "2013-06-26 17:41:28" },
  { :nombre => "Verduras", :descripcion => nil, :created_at => "2013-06-26 17:41:28", :updated_at => "2013-06-26 17:41:28" },
  { :nombre => "Otros", :descripcion => nil, :created_at => "2013-06-26 17:41:29", :updated_at => "2013-06-26 17:41:29" }
], :without_protection => true )



AreasPlates.create([
  { :area_id => nil, :plate_id => nil }
], :without_protection => true )



DayRegime.create([
  { :date => "2013-06-26", :regime_day => 4, :created_at => "2013-06-26 17:41:41", :updated_at => "2013-06-26 17:41:41" }
], :without_protection => true )



Ingredient.create([
  { :nombre => "carne", :precio => 250, :unidad => "gramos", :created_at => "2013-06-26 17:41:36", :updated_at => "2013-06-26 17:41:36" },
  { :nombre => "arroz", :precio => 100, :unidad => "gramos", :created_at => "2013-06-26 17:41:36", :updated_at => "2013-06-26 17:41:36" },
  { :nombre => "lechuga", :precio => 100, :unidad => "gramos", :created_at => "2013-06-26 17:41:37", :updated_at => "2013-06-26 17:41:37" },
  { :nombre => "papas", :precio => 200, :unidad => "gramos", :created_at => "2013-06-26 17:41:37", :updated_at => "2013-06-26 17:41:37" },
  { :nombre => "cebolla", :precio => 150, :unidad => "gramos", :created_at => "2013-06-26 17:41:37", :updated_at => "2013-06-26 17:41:37" },
  { :nombre => "pollo", :precio => 450, :unidad => "gramos", :created_at => "2013-06-26 17:41:37", :updated_at => "2013-06-26 17:41:37" },
  { :nombre => "champiñones", :precio => 450, :unidad => "gramos", :created_at => "2013-06-26 17:41:38", :updated_at => "2013-06-26 17:41:38" },
  { :nombre => "reineta", :precio => 450, :unidad => "gramos", :created_at => "2013-06-26 17:41:38", :updated_at => "2013-06-26 17:41:38" },
  { :nombre => "aceite", :precio => 10, :unidad => "ml", :created_at => "2013-06-26 17:41:38", :updated_at => "2013-06-26 17:41:38" },
  { :nombre => "sal", :precio => 5, :unidad => "gramos", :created_at => "2013-06-26 17:41:38", :updated_at => "2013-06-26 17:41:38" }
], :without_protection => true )



Order.create([
  { :horario => 1, :comentarios => "", :created_at => "2013-06-10 01:43:24", :updated_at => "2013-06-10 01:43:24", :order_list_id => 2, :regime_id => nil },
  { :horario => 1, :comentarios => "", :created_at => "2013-06-10 16:50:17", :updated_at => "2013-06-10 16:50:17", :order_list_id => 2, :regime_id => nil },
  { :horario => 2, :comentarios => "", :created_at => "2013-06-10 16:50:32", :updated_at => "2013-06-10 16:50:32", :order_list_id => 2, :regime_id => nil },
  { :horario => 8, :comentarios => "", :created_at => "2013-06-10 16:50:55", :updated_at => "2013-06-10 16:50:55", :order_list_id => 2, :regime_id => nil },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:45", :updated_at => "2013-06-12 16:46:45", :order_list_id => 3, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:45", :updated_at => "2013-06-12 16:46:45", :order_list_id => 4, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:45", :updated_at => "2013-06-12 16:46:45", :order_list_id => 5, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:45", :updated_at => "2013-06-12 16:46:45", :order_list_id => 6, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:46", :updated_at => "2013-06-12 16:46:46", :order_list_id => 7, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:46:46", :updated_at => "2013-06-12 16:46:46", :order_list_id => 8, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:50:58", :updated_at => "2013-06-12 16:50:58", :order_list_id => 9, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-12 16:50:58", :updated_at => "2013-06-12 16:50:58", :order_list_id => 10, :regime_id => 1 },
  { :horario => 4, :comentarios => nil, :created_at => "2013-06-12 16:50:58", :updated_at => "2013-06-12 16:50:58", :order_list_id => 11, :regime_id => 1 },
  { :horario => 8, :comentarios => nil, :created_at => "2013-06-12 16:50:58", :updated_at => "2013-06-12 16:50:58", :order_list_id => 12, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-12 16:50:59", :updated_at => "2013-06-12 16:50:59", :order_list_id => 13, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-12 16:50:59", :updated_at => "2013-06-12 16:50:59", :order_list_id => 14, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-26 17:41:43", :updated_at => "2013-06-26 17:41:43", :order_list_id => 15, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-26 17:41:43", :updated_at => "2013-06-26 17:41:43", :order_list_id => 16, :regime_id => 1 },
  { :horario => 4, :comentarios => nil, :created_at => "2013-06-26 17:41:44", :updated_at => "2013-06-26 17:41:44", :order_list_id => 17, :regime_id => 1 },
  { :horario => 8, :comentarios => nil, :created_at => "2013-06-26 17:41:44", :updated_at => "2013-06-26 17:41:44", :order_list_id => 18, :regime_id => 1 },
  { :horario => 1, :comentarios => nil, :created_at => "2013-06-26 17:41:44", :updated_at => "2013-06-26 17:41:44", :order_list_id => 19, :regime_id => 1 },
  { :horario => 2, :comentarios => nil, :created_at => "2013-06-26 17:41:44", :updated_at => "2013-06-26 17:41:44", :order_list_id => 20, :regime_id => 1 }
], :without_protection => true )



OrderList.create([
  { :patient_id => 46, :esPaciente => true, :created_at => "2013-06-26 17:41:42", :updated_at => "2013-06-26 17:41:42", :fecha => "2013-06-26", :dia => 4 },
  { :patient_id => 47, :esPaciente => true, :created_at => "2013-06-26 17:41:42", :updated_at => "2013-06-26 17:41:42", :fecha => "2013-06-26", :dia => 4 },
  { :patient_id => 48, :esPaciente => true, :created_at => "2013-06-26 17:41:42", :updated_at => "2013-06-26 17:41:42", :fecha => "2013-06-26", :dia => 4 },
  { :patient_id => 49, :esPaciente => true, :created_at => "2013-06-26 17:41:42", :updated_at => "2013-06-26 17:41:42", :fecha => "2013-06-26", :dia => 4 },
  { :patient_id => 46, :esPaciente => false, :created_at => "2013-06-26 17:41:43", :updated_at => "2013-06-26 17:41:43", :fecha => "2013-06-26", :dia => 4 },
  { :patient_id => 47, :esPaciente => false, :created_at => "2013-06-26 17:41:43", :updated_at => "2013-06-26 17:41:43", :fecha => "2013-06-26", :dia => 4 },
  { :patient_id => 48, :esPaciente => true, :created_at => "2013-06-26 19:42:40", :updated_at => "2013-06-26 19:42:54", :fecha => "2013-06-27", :dia => 5 }
], :without_protection => true )



Patient.create([
  { :nombre => "Pedro A", :num_pieza => "1A", :created_at => "2013-06-26 17:41:40", :updated_at => "2013-06-26 17:41:40", :rut => "17753853-4" },
  { :nombre => "Rodrigo A", :num_pieza => "2A", :created_at => "2013-06-26 17:41:40", :updated_at => "2013-06-26 17:41:40", :rut => "177533453-8" },
  { :nombre => "Fernando E", :num_pieza => "3A", :created_at => "2013-06-26 17:41:40", :updated_at => "2013-06-26 17:41:40", :rut => "13753853-3" },
  { :nombre => "Joaquin F", :num_pieza => "4A", :created_at => "2013-06-26 17:41:41", :updated_at => "2013-06-26 17:41:41", :rut => "16753853-2" },
  { :nombre => "Vicente V", :num_pieza => "5A", :created_at => "2013-06-26 17:41:41", :updated_at => "2013-06-26 17:41:41", :rut => "13753853-1" }
], :without_protection => true )



Plate.create([
  { :nombre => "Cafe", :calorias => nil, :tipo => 1, :created_at => "2013-06-26 17:41:29", :updated_at => "2013-06-26 17:41:29", :horario => 5, :description => nil },
  { :nombre => "Te", :calorias => nil, :tipo => 1, :created_at => "2013-06-26 17:41:29", :updated_at => "2013-06-26 17:41:29", :horario => 5, :description => nil },
  { :nombre => "Pan", :calorias => nil, :tipo => 2, :created_at => "2013-06-26 17:41:29", :updated_at => "2013-06-26 17:41:29", :horario => 5, :description => nil },
  { :nombre => "Jamon", :calorias => nil, :tipo => 3, :created_at => "2013-06-26 17:41:30", :updated_at => "2013-06-26 17:41:30", :horario => 5, :description => nil },
  { :nombre => "Palta", :calorias => nil, :tipo => 3, :created_at => "2013-06-26 17:41:30", :updated_at => "2013-06-26 17:41:30", :horario => 5, :description => nil },
  { :nombre => "Tortilla Francesa", :calorias => nil, :tipo => 3, :created_at => "2013-06-26 17:41:30", :updated_at => "2013-06-26 17:41:30", :horario => 5, :description => nil },
  { :nombre => "Queso", :calorias => nil, :tipo => 3, :created_at => "2013-06-26 17:41:30", :updated_at => "2013-06-26 17:41:30", :horario => 5, :description => nil },
  { :nombre => "Mantequilla", :calorias => nil, :tipo => 4, :created_at => "2013-06-26 17:41:31", :updated_at => "2013-06-26 17:41:31", :horario => 5, :description => nil },
  { :nombre => "Mermelada", :calorias => nil, :tipo => 4, :created_at => "2013-06-26 17:41:31", :updated_at => "2013-06-26 17:41:31", :horario => 5, :description => nil },
  { :nombre => "Manjar", :calorias => nil, :tipo => 4, :created_at => "2013-06-26 17:41:31", :updated_at => "2013-06-26 17:41:31", :horario => 5, :description => nil },
  { :nombre => "Miel", :calorias => nil, :tipo => 4, :created_at => "2013-06-26 17:41:31", :updated_at => "2013-06-26 17:41:31", :horario => 5, :description => nil },
  { :nombre => "Jugo naranja", :calorias => nil, :tipo => 5, :created_at => "2013-06-26 17:41:32", :updated_at => "2013-06-26 17:41:32", :horario => 5, :description => nil },
  { :nombre => "Yogurt", :calorias => nil, :tipo => 5, :created_at => "2013-06-26 17:41:32", :updated_at => "2013-06-26 17:41:32", :horario => 5, :description => nil },
  { :nombre => "Yogurt", :calorias => nil, :tipo => 5, :created_at => "2013-06-26 17:41:32", :updated_at => "2013-06-26 17:41:32", :horario => 5, :description => nil },
  { :nombre => "Pie de limon", :calorias => nil, :tipo => 6, :created_at => "2013-06-26 17:41:32", :updated_at => "2013-06-26 17:41:32", :horario => 5, :description => nil },
  { :nombre => "2 Palmeritas", :calorias => nil, :tipo => 6, :created_at => "2013-06-26 17:41:33", :updated_at => "2013-06-26 17:41:33", :horario => 5, :description => nil },
  { :nombre => "Bollo", :calorias => nil, :tipo => 6, :created_at => "2013-06-26 17:41:33", :updated_at => "2013-06-26 17:41:33", :horario => 5, :description => nil },
  { :nombre => "Galletas", :calorias => nil, :tipo => 6, :created_at => "2013-06-26 17:41:33", :updated_at => "2013-06-26 17:41:33", :horario => 5, :description => nil },
  { :nombre => "Consome", :calorias => nil, :tipo => 7, :created_at => "2013-06-26 17:41:33", :updated_at => "2013-06-26 17:41:33", :horario => 10, :description => nil },
  { :nombre => "Albahaca y dados de tomate, palta, queso fresco", :calorias => nil, :tipo => 7, :created_at => "2013-06-26 17:41:34", :updated_at => "2013-06-26 17:41:34", :horario => 10, :description => nil },
  { :nombre => "Quiche loreine", :calorias => nil, :tipo => 7, :created_at => "2013-06-26 17:41:34", :updated_at => "2013-06-26 17:41:34", :horario => 10, :description => nil },
  { :nombre => "Reineta al horno", :calorias => nil, :tipo => 8, :created_at => "2013-06-26 17:41:34", :updated_at => "2013-06-26 17:41:34", :horario => 10, :description => nil },
  { :nombre => "Bistec de lomo c/ salsa champiñon", :calorias => nil, :tipo => 8, :created_at => "2013-06-26 17:41:34", :updated_at => "2013-06-26 17:41:34", :horario => 10, :description => nil },
  { :nombre => "Verduras a la mantequilla: Zapallito, zanahoria, champiñones", :calorias => nil, :tipo => 9, :created_at => "2013-06-26 17:41:35", :updated_at => "2013-06-26 17:41:35", :horario => 10, :description => nil },
  { :nombre => "Arroz", :calorias => nil, :tipo => 9, :created_at => "2013-06-26 17:41:35", :updated_at => "2013-06-26 17:41:35", :horario => 10, :description => nil },
  { :nombre => "Pure", :calorias => nil, :tipo => 9, :created_at => "2013-06-26 17:41:35", :updated_at => "2013-06-26 17:41:35", :horario => 10, :description => nil },
  { :nombre => "Verduras a la mantequilla: Zapallito, zanahoria, champiñones", :calorias => nil, :tipo => 9, :created_at => "2013-06-26 17:41:35", :updated_at => "2013-06-26 17:41:35", :horario => 10, :description => nil },
  { :nombre => "Helado", :calorias => nil, :tipo => 10, :created_at => "2013-06-26 17:41:36", :updated_at => "2013-06-26 17:41:36", :horario => 2, :description => nil },
  { :nombre => "Fruta", :calorias => nil, :tipo => 10, :created_at => "2013-06-26 17:41:36", :updated_at => "2013-06-26 17:41:36", :horario => 2, :description => nil }
], :without_protection => true )



PlateIngredient.create([
  { :cantidad => 5, :created_at => "2013-06-06 14:30:50", :updated_at => "2013-06-06 14:30:50", :plate_id => 141, :ingredient_id => 28 },
  { :cantidad => 5, :created_at => "2013-06-06 14:30:50", :updated_at => "2013-06-06 14:30:50", :plate_id => 141, :ingredient_id => 35 },
  { :cantidad => 5, :created_at => "2013-06-06 14:30:50", :updated_at => "2013-06-06 14:30:50", :plate_id => 141, :ingredient_id => 36 },
  { :cantidad => 3, :created_at => "2013-06-06 14:30:50", :updated_at => "2013-06-06 14:30:50", :plate_id => 138, :ingredient_id => 34 },
  { :cantidad => 2, :created_at => "2013-06-06 14:30:51", :updated_at => "2013-06-06 14:30:51", :plate_id => 139, :ingredient_id => 27 },
  { :cantidad => 2, :created_at => "2013-06-06 14:30:51", :updated_at => "2013-06-06 14:30:51", :plate_id => 139, :ingredient_id => 33 },
  { :cantidad => 5, :created_at => "2013-06-06 15:07:37", :updated_at => "2013-06-06 15:07:37", :plate_id => 170, :ingredient_id => 38 },
  { :cantidad => 5, :created_at => "2013-06-06 15:07:37", :updated_at => "2013-06-06 15:07:37", :plate_id => 170, :ingredient_id => 45 },
  { :cantidad => 5, :created_at => "2013-06-06 15:07:38", :updated_at => "2013-06-06 15:07:38", :plate_id => 170, :ingredient_id => 46 },
  { :cantidad => 3, :created_at => "2013-06-06 15:07:38", :updated_at => "2013-06-06 15:07:38", :plate_id => 167, :ingredient_id => 44 },
  { :cantidad => 2, :created_at => "2013-06-06 15:07:38", :updated_at => "2013-06-06 15:07:38", :plate_id => 168, :ingredient_id => 37 },
  { :cantidad => 2, :created_at => "2013-06-06 15:07:38", :updated_at => "2013-06-06 15:07:38", :plate_id => 168, :ingredient_id => 43 },
  { :cantidad => 5, :created_at => "2013-06-06 15:12:32", :updated_at => "2013-06-06 15:12:32", :plate_id => 199, :ingredient_id => 48 },
  { :cantidad => 5, :created_at => "2013-06-06 15:12:32", :updated_at => "2013-06-06 15:12:32", :plate_id => 199, :ingredient_id => 55 },
  { :cantidad => 5, :created_at => "2013-06-06 15:12:33", :updated_at => "2013-06-06 15:12:33", :plate_id => 199, :ingredient_id => 56 },
  { :cantidad => 3, :created_at => "2013-06-06 15:12:33", :updated_at => "2013-06-06 15:12:33", :plate_id => 196, :ingredient_id => 54 },
  { :cantidad => 2, :created_at => "2013-06-06 15:12:33", :updated_at => "2013-06-06 15:12:33", :plate_id => 197, :ingredient_id => 47 },
  { :cantidad => 2, :created_at => "2013-06-06 15:12:33", :updated_at => "2013-06-06 15:12:33", :plate_id => 197, :ingredient_id => 53 },
  { :cantidad => 5, :created_at => "2013-06-06 15:19:07", :updated_at => "2013-06-06 15:19:07", :plate_id => 228, :ingredient_id => 58 },
  { :cantidad => 5, :created_at => "2013-06-06 15:19:07", :updated_at => "2013-06-06 15:19:07", :plate_id => 228, :ingredient_id => 65 },
  { :cantidad => 5, :created_at => "2013-06-06 15:19:08", :updated_at => "2013-06-06 15:19:08", :plate_id => 228, :ingredient_id => 66 },
  { :cantidad => 3, :created_at => "2013-06-06 15:19:08", :updated_at => "2013-06-06 15:19:08", :plate_id => 225, :ingredient_id => 64 },
  { :cantidad => 2, :created_at => "2013-06-06 15:19:08", :updated_at => "2013-06-06 15:19:08", :plate_id => 226, :ingredient_id => 57 },
  { :cantidad => 2, :created_at => "2013-06-06 15:19:08", :updated_at => "2013-06-06 15:19:08", :plate_id => 226, :ingredient_id => 63 },
  { :cantidad => 2, :created_at => "2013-06-11 00:07:26", :updated_at => "2013-06-11 00:07:26", :plate_id => 226, :ingredient_id => 60 },
  { :cantidad => 5, :created_at => "2013-06-12 16:14:03", :updated_at => "2013-06-12 16:14:03", :plate_id => 257, :ingredient_id => 68 },
  { :cantidad => 5, :created_at => "2013-06-12 16:14:03", :updated_at => "2013-06-12 16:14:03", :plate_id => 257, :ingredient_id => 75 },
  { :cantidad => 5, :created_at => "2013-06-12 16:14:03", :updated_at => "2013-06-12 16:14:03", :plate_id => 257, :ingredient_id => 76 },
  { :cantidad => 3, :created_at => "2013-06-12 16:14:03", :updated_at => "2013-06-12 16:14:03", :plate_id => 254, :ingredient_id => 74 },
  { :cantidad => 2, :created_at => "2013-06-12 16:14:04", :updated_at => "2013-06-12 16:14:04", :plate_id => 255, :ingredient_id => 67 },
  { :cantidad => 2, :created_at => "2013-06-12 16:14:04", :updated_at => "2013-06-12 16:14:04", :plate_id => 255, :ingredient_id => 73 },
  { :cantidad => 5, :created_at => "2013-06-12 16:44:06", :updated_at => "2013-06-12 16:44:06", :plate_id => 286, :ingredient_id => 78 },
  { :cantidad => 5, :created_at => "2013-06-12 16:44:06", :updated_at => "2013-06-12 16:44:06", :plate_id => 286, :ingredient_id => 85 },
  { :cantidad => 5, :created_at => "2013-06-12 16:44:07", :updated_at => "2013-06-12 16:44:07", :plate_id => 286, :ingredient_id => 86 },
  { :cantidad => 3, :created_at => "2013-06-12 16:44:07", :updated_at => "2013-06-12 16:44:07", :plate_id => 283, :ingredient_id => 84 },
  { :cantidad => 2, :created_at => "2013-06-12 16:44:07", :updated_at => "2013-06-12 16:44:07", :plate_id => 284, :ingredient_id => 77 },
  { :cantidad => 2, :created_at => "2013-06-12 16:44:07", :updated_at => "2013-06-12 16:44:07", :plate_id => 284, :ingredient_id => 83 },
  { :cantidad => 5, :created_at => "2013-06-12 16:46:40", :updated_at => "2013-06-12 16:46:40", :plate_id => 315, :ingredient_id => 88 },
  { :cantidad => 5, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 315, :ingredient_id => 95 },
  { :cantidad => 5, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 315, :ingredient_id => 96 },
  { :cantidad => 3, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 312, :ingredient_id => 94 },
  { :cantidad => 2, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 313, :ingredient_id => 87 },
  { :cantidad => 2, :created_at => "2013-06-12 16:46:41", :updated_at => "2013-06-12 16:46:41", :plate_id => 313, :ingredient_id => 93 },
  { :cantidad => 5, :created_at => "2013-06-12 16:50:52", :updated_at => "2013-06-12 16:50:52", :plate_id => 344, :ingredient_id => 98 },
  { :cantidad => 5, :created_at => "2013-06-12 16:50:52", :updated_at => "2013-06-12 16:50:52", :plate_id => 344, :ingredient_id => 105 },
  { :cantidad => 5, :created_at => "2013-06-12 16:50:53", :updated_at => "2013-06-12 16:50:53", :plate_id => 344, :ingredient_id => 106 },
  { :cantidad => 3, :created_at => "2013-06-12 16:50:53", :updated_at => "2013-06-12 16:50:53", :plate_id => 341, :ingredient_id => 104 },
  { :cantidad => 2, :created_at => "2013-06-12 16:50:53", :updated_at => "2013-06-12 16:50:53", :plate_id => 342, :ingredient_id => 97 },
  { :cantidad => 2, :created_at => "2013-06-12 16:50:53", :updated_at => "2013-06-12 16:50:53", :plate_id => 342, :ingredient_id => 103 },
  { :cantidad => 5, :created_at => "2013-06-26 17:41:38", :updated_at => "2013-06-26 17:41:38", :plate_id => 402, :ingredient_id => 108 },
  { :cantidad => 5, :created_at => "2013-06-26 17:41:39", :updated_at => "2013-06-26 17:41:39", :plate_id => 402, :ingredient_id => 115 },
  { :cantidad => 5, :created_at => "2013-06-26 17:41:39", :updated_at => "2013-06-26 17:41:39", :plate_id => 402, :ingredient_id => 116 },
  { :cantidad => 3, :created_at => "2013-06-26 17:41:39", :updated_at => "2013-06-26 17:41:39", :plate_id => 399, :ingredient_id => 114 },
  { :cantidad => 2, :created_at => "2013-06-26 17:41:39", :updated_at => "2013-06-26 17:41:39", :plate_id => 400, :ingredient_id => 107 },
  { :cantidad => 2, :created_at => "2013-06-26 17:41:40", :updated_at => "2013-06-26 17:41:40", :plate_id => 400, :ingredient_id => 113 }
], :without_protection => true )



Regime.create([
  { :nombre => "Régimen para Diabetes", :created_at => "2013-05-24 13:14:13", :updated_at => "2013-06-26 19:47:05" }
], :without_protection => true )



RegimePlate.create([
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 379, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 378, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 380, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 382, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 386, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 387, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 388, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 390, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 393, :regime_id => 1, :horario => 1 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 397, :regime_id => 1, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 400, :regime_id => 1, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 402, :regime_id => 1, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 405, :regime_id => 1, :horario => 2 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 379, :regime_id => 1, :horario => 4 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 380, :regime_id => 1, :horario => 4 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 393, :regime_id => 1, :horario => 4 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 397, :regime_id => 1, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 399, :regime_id => 1, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 401, :regime_id => 1, :horario => 8 },
  { :dia => 1, :created_at => "2013-06-26 19:46:12", :updated_at => "2013-06-26 19:46:12", :plate_id => 405, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 379, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 380, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 381, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 385, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 389, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 392, :regime_id => 1, :horario => 1 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 396, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 397, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 399, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 401, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 405, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 406, :regime_id => 1, :horario => 2 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 378, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 379, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 380, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 393, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 392, :regime_id => 1, :horario => 4 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 396, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 397, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 399, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 402, :regime_id => 1, :horario => 8 },
  { :dia => 2, :created_at => "2013-06-26 19:48:01", :updated_at => "2013-06-26 19:48:01", :plate_id => 405, :regime_id => 1, :horario => 8 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 378, :regime_id => 1, :horario => 1 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 380, :regime_id => 1, :horario => 1 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 381, :regime_id => 1, :horario => 1 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 385, :regime_id => 1, :horario => 1 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 389, :regime_id => 1, :horario => 1 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 392, :regime_id => 1, :horario => 1 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 396, :regime_id => 1, :horario => 2 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 399, :regime_id => 1, :horario => 2 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 401, :regime_id => 1, :horario => 2 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 405, :regime_id => 1, :horario => 2 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 378, :regime_id => 1, :horario => 4 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 380, :regime_id => 1, :horario => 4 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 392, :regime_id => 1, :horario => 4 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 396, :regime_id => 1, :horario => 8 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 399, :regime_id => 1, :horario => 8 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 401, :regime_id => 1, :horario => 8 },
  { :dia => 3, :created_at => "2013-06-26 19:51:41", :updated_at => "2013-06-26 19:51:41", :plate_id => 405, :regime_id => 1, :horario => 8 }
], :without_protection => true )





Role.create([
  { :name => "admin", :resource_id => nil, :resource_type => nil, :created_at => "2013-05-24 13:01:22", :updated_at => "2013-05-24 13:01:22" },
  { :name => "nutricionista", :resource_id => nil, :resource_type => nil, :created_at => "2013-05-24 13:01:23", :updated_at => "2013-05-24 13:01:23" },
  { :name => "cocina", :resource_id => nil, :resource_type => nil, :created_at => "2013-05-24 13:01:23", :updated_at => "2013-05-24 13:01:23" }
], :without_protection => true )



User.create([
  { :email => "user@example.com", :encrypted_password => "$2a$10$Esiq99QTQn5J/WJku3/AL.lUHfbLplRq0/qSBD6WeksAifIsN9gwe", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 17, :current_sign_in_at => "2013-06-26 18:42:00", :last_sign_in_at => "2013-06-26 18:31:14", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-05-24 13:01:23", :updated_at => "2013-06-26 18:42:00", :name => "First User", :rut => "12345678-9" }
], :without_protection => true )


